creation_rules:
  - path_regex: 'vault/system/BerkeleyMonoVariable\.ttf\.enc\.yaml$'
    age: 'age1mtk5tx0xrr5lwyjurfyd2uz2kl0549vx922p2lvvm4ck9jfpc96su8hwhd,age1vm9c9kvzsdrrrn8kndjm7ea79ns0lnw3u30u4enfwca25m0xheeqw7etzm'
  - path_regex: 'vault/system/.*\.enc\.ya?ml$'
    age: 'age1mtk5tx0xrr5lwyjurfyd2uz2kl0549vx922p2lvvm4ck9jfpc96su8hwhd'
  - path_regex: 'vault/projects/.*\.enc\.ya?ml$'
    age: 'age1vm9c9kvzsdrrrn8kndjm7ea79ns0lnw3u30u4enfwca25m0xheeqw7etzm'
